name: 'VHS Action'
description: 'Run VHS to render terminal videos'
branding:
  icon: film
  color: purple
inputs:
  version:
    description: VHS version
    default: latest
  path:
    description: 'The tape file path'
    default: ''
  token:
    description: Used to pull VHS from Github
    default: ${{ github.token }}
  install-fonts:
    description: Install extra fonts
    default: 'false'
  install-only:
    description: Only install VHS without running it
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/index.js'
